# Generated by Django 3.1.3 on 2020-11-30 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import werewolves.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VILLAGER', 'VILLAGER'), ('WOLF', 'WOLF'), ('SEER', 'SEER'), ('GUARD', 'GUARD'), ('NONE', 'NOT ASSIGNED')], default='NONE', max_length=30)),
                ('status', models.CharField(choices=[('ALIVE', 'ALIVE'), ('OUT', 'OUT')], default='ALIVE', max_length=30)),
                ('vote', models.IntegerField(null=True)),
                ('kill', models.IntegerField(null=True)),
                ('speech', models.BooleanField(default=False)),
                ('id_in_game', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=200)),
                ('message_sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guard_previous_id', models.IntegerField(null=True)),
                ('first_speaker_id', models.IntegerField(null=True)),
                ('step', models.CharField(choices=[('WOLF', 'WOLF'), ('GUARD', 'GUARD'), ('SEER', 'SEER'), ('ANNOUNCE', 'ANNOUNCE'), ('SPEECH', 'SPEECH'), ('VOTE', 'VOTE'), ('END_VOTE', 'END_VOTE'), ('END_GAME', 'END_GAME'), ('NONE', 'NOT ASSIGNED')], default=werewolves.models.GameStep['NONE'], max_length=30)),
                ('winning', models.BooleanField(default=None, null=True)),
                ('wolves', models.CharField(blank=True, max_length=6, null=True)),
                ('seer', models.CharField(blank=True, max_length=6, null=True)),
                ('guard', models.CharField(blank=True, max_length=6, null=True)),
                ('villagers', models.CharField(blank=True, max_length=6, null=True)),
                ('current_speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='is_current_speaker', to='werewolves.player')),
                ('guard_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='is_guard_target', to='werewolves.player')),
                ('seer_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='is_seer_target', to='werewolves.player')),
                ('vote_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='is_vote_target', to='werewolves.player')),
                ('wolves_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='is_wolf_target', to='werewolves.player')),
            ],
        ),
    ]
