# Generated by Django 3.1.3 on 2020-11-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='guard_select',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamestatus',
            name='seer_select',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamestatus',
            name='speaker_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamestatus',
            name='vote_select',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamestatus',
            name='wolves_select',
            field=models.IntegerField(null=True),
        ),
    ]
