# Generated by Django 3.1.3 on 2020-12-01 23:19

from django.db import migrations, models
import werewolves.models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolves', '0002_auto_20201130_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestatus',
            name='step',
            field=models.CharField(choices=[('WOLF', 'WOLF'), ('GUARD', 'GUARD'), ('SEER', 'SEER'), ('ANNOUNCE', 'ANNOUNCE'), ('SPEECH', 'SPEECH'), ('VOTE', 'VOTE'), ('END_VOTE', 'END_VOTE'), ('END_DAY', 'END_DAY'), ('END_GAME', 'END_GAME'), ('NONE', 'NOT ASSIGNED')], default=werewolves.models.GameStep['NONE'], max_length=30),
        ),
    ]
