# Generated by Django 3.1.3 on 2020-12-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolves', '0003_auto_20201201_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='current_speaker_name',
            field=models.CharField(default='NONE', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gamestatus',
            name='guard_target_name',
            field=models.CharField(default='NONE', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gamestatus',
            name='seer_target_name',
            field=models.CharField(default='NONE', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gamestatus',
            name='vote_target_name',
            field=models.CharField(default='NONE', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gamestatus',
            name='wolves_target_name',
            field=models.CharField(default='NONE', max_length=30, null=True),
        ),
    ]
