# Generated by Django 3.1.3 on 2020-12-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolves', '0005_gamestatus_seer_target_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='current_speaker_role',
            field=models.CharField(default='NONE', max_length=30, null=True),
        ),
    ]
