# Generated by Django 3.1.3 on 2020-12-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werewolves', '0006_gamestatus_current_speaker_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestatus',
            name='current_speaker',
        ),
        migrations.RemoveField(
            model_name='gamestatus',
            name='guard_target',
        ),
        migrations.RemoveField(
            model_name='gamestatus',
            name='seer_target',
        ),
        migrations.RemoveField(
            model_name='gamestatus',
            name='vote_target',
        ),
        migrations.RemoveField(
            model_name='gamestatus',
            name='wolves_target',
        ),
    ]
