# Generated by Django 3.1.3 on 2020-12-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolves', '0007_auto_20201204_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='vote',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
