# Generated by Django 3.1.3 on 2020-12-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolves', '0008_gamestatus_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='trigger_id',
            field=models.IntegerField(null=True),
        ),
    ]
